"use client";

import { FormEvent, useState } from "react";
import { useRouter } from "next/navigation";
import { motion } from "framer-motion";
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "../../components/ui/Card";
import { Button } from "../../components/ui/Button";
import { CheckCircle2, Zap, Search, Layout, Sparkles, Smartphone, BarChart3, Lock } from "lucide-react";

function FeatureCard({ icon: Icon, title, desc }: { icon: any; title: string; desc: string }) {
  return (
    <Card className="group h-full transition-all hover:border-foreground/20">
      <CardContent className="p-6">
        <div className="mb-4 inline-flex rounded-lg bg-secondary p-3 text-secondary-foreground transition-transform group-hover:scale-105">
          <Icon className="h-6 w-6" />
        </div>
        <h3 className="mb-2 text-lg font-semibold text-foreground">{title}</h3>
        <p className="text-sm text-muted-foreground leading-relaxed">{desc}</p>
      </CardContent>
    </Card>
  );
}

export default function MarketingPage() {
  const router = useRouter();
  const [url, setUrl] = useState("");

  const onSubmit = (e: FormEvent) => {
    e.preventDefault();
    const target = url.trim();
    if (!target) return;
    router.push(`/audit?url=${encodeURIComponent(target)}&autoStart=1`);
  };

  return (
    <main className="flex min-h-screen flex-col pt-14">
      {/* Hero Section */}
      <section className="relative overflow-hidden bg-background">
        <div className="mx-auto flex max-w-6xl flex-col items-center px-6 py-24 text-center md:py-32">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.5 }}
            className="mb-8 inline-flex items-center rounded-full border border-border bg-secondary px-4 py-2 text-sm font-medium text-secondary-foreground"
          >
            <Sparkles className="mr-2 h-4 w-4" />
            Join 10,000+ developers shipping better websites
          </motion.div>
          <motion.h1 
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.5, delay: 0.1 }}
            className="mb-6 max-w-4xl text-balance text-5xl font-extrabold tracking-tight text-foreground md:text-7xl"
          >
            Live Audits + Groq AI Insights
          </motion.h1>
          <motion.p 
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.5, delay: 0.2 }}
            className="mb-10 max-w-2xl text-lg text-muted-foreground md:text-xl"
          >
            Get a comprehensive breakdown of your performance, SEO, accessibility, and UI/UX with actionable insights generated by advanced AI.
          </motion.p>

          <motion.form 
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.5, delay: 0.3 }}
            onSubmit={onSubmit} 
            className="relative w-full max-w-2xl"
          >
            <div className="relative flex flex-col sm:flex-row items-stretch sm:items-center rounded-xl border border-border bg-card p-2 shadow-sm focus-within:ring-2 focus-within:ring-foreground transition-all gap-2 sm:gap-0">
              <div className="relative flex flex-1 items-center">
                <Search className="absolute left-4 h-5 w-5 text-muted-foreground" />
                <input
                  value={url}
                  onChange={(e) => setUrl(e.target.value)}
                  placeholder="https://yourwebsite.com"
                  className="w-full bg-transparent py-3 pl-12 pr-4 text-lg text-foreground placeholder:text-muted-foreground focus:outline-none"
                  required
                  type="url"
                />
              </div>
              <Button type="submit" variant="default" size="lg" className="px-8 font-semibold w-full sm:w-auto shrink-0">
                Analyze
              </Button>
            </div>
          </motion.form>
          
          <motion.div 
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            transition={{ delay: 1 }}
            className="mt-16 rounded-xl border border-border bg-card p-4 shadow-sm md:p-6"
          >
            <div className="flex items-center justify-center space-x-2 text-sm text-muted-foreground">
              <div className="h-2.5 w-2.5 animate-pulse rounded-full bg-success"></div>
              <span>Live Scanning Engine Online - No simulated results</span>
            </div>
          </motion.div>
        </div>
      </section>

      {/* Features Section */}
      <section id="features" className="border-t border-border bg-card/50 py-24">
        <div className="mx-auto max-w-7xl px-6">
          <div className="mb-16 text-center">
            <h2 className="mb-4 text-3xl font-bold tracking-tight text-foreground md:text-5xl">Everything you need to perfect your site</h2>
            <p className="mx-auto max-w-2xl text-lg text-muted-foreground">
              We process 50+ data points including visual captures, performance metrics, and DOM structures to give you precise diagnostics.
            </p>
          </div>
          <div className="grid gap-6 md:grid-cols-2 lg:grid-cols-3">
            <FeatureCard icon={Smartphone} title="Mobile-First Audit" desc="Real device emulation for tap-targets, responsiveness, and mobile-specific accessibility checks." />
            <FeatureCard icon={Zap} title="Lighthouse Core" desc="Industry standard performance, SEO, and accessibility metrics extracted directly via headless Chrome." />
            <FeatureCard icon={Sparkles} title="Groq AI" desc="Groq AI Insights explains exactly how technical fixes impact your business metrics in plain English." />
            <FeatureCard icon={Search} title="Live DOM Parsing" desc="Extraction of titles, metas, headings, and CTAs right from the target HTML for precise SEO checks." />
            <FeatureCard icon={Layout} title="Visual Sandbox" desc="Full-page desktop and mobile screenshots captured for visual regression and UI/UX evaluation." />
            <FeatureCard icon={BarChart3} title="Audit History" desc="Persisted audits safely stored in PostgreSQL with complete time-stamped delta tracking." />
          </div>
        </div>
      </section>

      {/* Testimonials / Trust Section */}
      <section id="testimonials" className="border-t border-border bg-background py-24">
        <div className="mx-auto max-w-7xl px-6">
          <h2 className="mb-12 text-center text-3xl font-bold text-foreground">Trusted by developers and agencies</h2>
          <div className="grid gap-8 md:grid-cols-3">
            {[1, 2, 3].map((i) => (
              <Card key={i} className="h-full">
                <CardContent className="p-6">
                  <div className="mb-4 flex gap-1 text-foreground">
                    {[...Array(5)].map((_, j) => <Sparkles key={j} className="h-4 w-4 fill-current" />)}
                  </div>
                  <p className="mb-6 text-foreground/80 leading-relaxed max-w-sm">"SiteBlitz fundamentally changed how we deliver websites. We use it to automatically generate audit reports for our clients before launch. It's incredibly fast and accurate."</p>
                  <div className="flex items-center gap-3">
                    <div className="h-10 w-10 rounded-full bg-secondary" />
                    <div>
                      <div className="text-sm font-semibold text-foreground">Sarah Jenkins</div>
                      <div className="text-xs text-muted-foreground">Lead Developer, WebStudio</div>
                    </div>
                  </div>
                </CardContent>
              </Card>
            ))}
          </div>
        </div>
      </section>

      {/* Pricing Section */}
      <section id="pricing" className="border-t border-border bg-card/50 py-24">
        <div className="mx-auto max-w-5xl px-6">
          <div className="mb-16 text-center">
            <h2 className="mb-4 text-3xl font-bold tracking-tight text-foreground md:text-5xl">Simple, transparent pricing</h2>
            <p className="text-lg text-muted-foreground">Start for free, upgrade when you need more power.</p>
          </div>
          
          <div className="grid gap-8 md:grid-cols-2 lg:gap-12">
            {/* Free Tier */}
            <Card className="flex flex-col">
              <CardHeader>
                <CardTitle className="text-2xl">Starter</CardTitle>
                <CardDescription>Perfect for side projects and individual developers.</CardDescription>
                <div className="mt-4 flex items-baseline text-5xl font-extrabold text-foreground">
                  $0
                  <span className="ml-1 text-xl font-medium text-muted-foreground">/mo</span>
                </div>
              </CardHeader>
              <CardContent className="flex flex-1 flex-col">
                <ul className="flex flex-1 flex-col gap-4 text-sm text-foreground/80">
                  {['100 live audits per month', 'Core Lighthouse metrics', 'Desktop screenshots', '7-day audit history', 'Community support'].map((feature) => (
                    <li key={feature} className="flex items-center gap-3">
                      <CheckCircle2 className="h-5 w-5 text-success" />
                      {feature}
                    </li>
                  ))}
                </ul>
                <Button variant="secondary" className="mt-8 w-full">Start for Free</Button>
              </CardContent>
            </Card>

            {/* Pro Tier */}
            <Card className="relative flex flex-col border-foreground">
              <div className="absolute -top-3 left-0 right-0 mx-auto w-fit rounded-full bg-foreground px-3 py-1 text-xs font-semibold text-background">
                Most Popular
              </div>
              <CardHeader>
                <CardTitle className="text-2xl">Pro</CardTitle>
                <CardDescription>For agencies and power users needing deep analytics.</CardDescription>
                <div className="mt-4 flex items-baseline text-5xl font-extrabold text-foreground">
                  $29
                  <span className="ml-1 text-xl font-medium text-muted-foreground">/mo</span>
                </div>
              </CardHeader>
              <CardContent className="flex flex-1 flex-col">
                <ul className="flex flex-1 flex-col gap-4 text-sm text-foreground/80">
                  {['Unlimited live audits', 'Full AI Business Insights', 'Mobile & Desktop visual capture', 'Unlimited audit history', 'Export to PDF/CSV', 'Priority support'].map((feature) => (
                    <li key={feature} className="flex items-center gap-3">
                      <CheckCircle2 className="h-5 w-5 text-success" />
                      {feature}
                    </li>
                  ))}
                </ul>
                <Button variant="default" className="mt-8 w-full">Upgrade to Pro</Button>
              </CardContent>
            </Card>
          </div>
        </div>
      </section>
    </main>
  );
}
