import { AUDIT_PROMPTS, COLOR_PSYCHOLOGY_TIPS } from "./prompts";

export type AuditScores = {
  uiux: number;
  perf: number;
  mobile: number;
  access: number;
  seo: number;
  leads: number;
  overall: number;
};

export type AuditResult = {
  scores: AuditScores;
  issues: string[];
  fixes: string[];
  leadBoost: string;
  benchmark: { you: number; competitorsAvg: number };
  promptsUsed: typeof AUDIT_PROMPTS;
  colorSuggestions: string[];
};

export type ContentSuggestion = {
  type: "title" | "metaDescription" | "h1";
  current: string;
  suggested: string;
  reason: string;
  confidence: number;
  guidelineBullets: string[];
};

/** Exported for tests — strips tags/entities from a fragment (e.g. first H1 inner HTML). */
export function stripHtmlForContentPreview(fragment: string): string {
  let s = String(fragment || "");
  s = s.replace(/<script[\s\S]*?<\/script>/gi, " ").replace(/<style[\s\S]*?<\/style>/gi, " ");
  let prev = "";
  while (prev !== s) {
    prev = s;
    s = s.replace(/<[^>]+>/g, " ");
  }
  s = decodeHtmlEntities(s);
  return s.replace(/\s+/g, " ").trim();
}

function decodeHtmlEntities(s: string): string {
  return s
    .replace(/&nbsp;/gi, " ")
    .replace(/&#x([0-9a-f]+);/gi, (_, h) => {
      const cp = parseInt(h, 16);
      return Number.isFinite(cp) ? String.fromCodePoint(cp) : _;
    })
    .replace(/&#(\d+);/g, (_, d) => {
      const cp = parseInt(d, 10);
      return Number.isFinite(cp) ? String.fromCodePoint(cp) : _;
    })
    .replace(/&amp;/g, "&")
    .replace(/&lt;/g, "<")
    .replace(/&gt;/g, ">")
    .replace(/&quot;/g, '"')
    .replace(/&#39;/g, "'");
}

function normalizeContentField(stripped: string): string {
  const t = stripped.trim();
  return t.length > 0 ? t : "Missing";
}

function isErrorLikeText(value: string): boolean {
  const t = String(value || "").toLowerCase();
  if (!t || t === "missing") return false;
  return /(^\s*(error[:-]|403|404|429|500|502|503)\b|\b\d{3}\s+error\b|request could not be satisfied|generated by cloudfront|access denied|\bforbidden\b|service unavailable|temporarily unavailable|\bnot found\b|degraded-fallback)/i.test(
    t
  );
}

function isLikelyErrorPage(html: string): boolean {
  const plain = stripHtmlForContentPreview(String(html || "")).toLowerCase();
  if (plain.includes("degraded-fallback")) return true;
  const hardSignals = [
    "request could not be satisfied",
    "generated by cloudfront",
    "access denied",
    "forbidden",
    "not found",
    "service unavailable",
    "temporarily unavailable",
    "degraded-fallback",
  ];
  const hardSignalCount = hardSignals.reduce((acc, s) => acc + (plain.includes(s) ? 1 : 0), 0);
  const hasStatusWithErrorWord = /\b(403|404|429|500|502|503)\b\s*(error|forbidden|not found|bad gateway|service unavailable)?/i.test(plain);

  // Require stronger evidence to avoid false positives on regular pages.
  if (hardSignalCount >= 2) return true;
  if (hardSignalCount >= 1 && hasStatusWithErrorWord) return true;
  return false;
}

function sanitizeCurrentField(value: string): string {
  if (value === "Missing") return value;
  return isErrorLikeText(value) ? "Missing" : value;
}

function extractBrandHint(title: string): string | null {
  if (!title || title === "Missing") return null;
  if (isErrorLikeText(title)) return null;
  const part = title.split(/\s*[|\u2013\-–:]\s*/)[0].trim();
  if (part.length >= 2 && part.length <= 48) return part;
  return null;
}

function compactSpaces(text: string): string {
  return String(text || "").replace(/\s+/g, " ").trim();
}

function trimWords(text: string, maxWords: number): string {
  const words = compactSpaces(text).split(" ").filter(Boolean);
  return words.slice(0, maxWords).join(" ");
}

function trimChars(text: string, maxChars: number): string {
  const t = compactSpaces(text);
  if (t.length <= maxChars) return t;
  return t.slice(0, Math.max(0, maxChars - 1)).trimEnd() + "...";
}

function toSentenceCase(text: string): string {
  const t = compactSpaces(text);
  if (!t) return "";
  return t.charAt(0).toUpperCase() + t.slice(1);
}

function buildTopicPhrase(values: string[]): string {
  const stop = new Set([
    "the",
    "and",
    "for",
    "with",
    "your",
    "this",
    "that",
    "from",
    "home",
    "welcome",
    "page",
    "company",
    "best",
    "top",
    "official",
  ]);

  const joined = values
    .filter((v) => v && v !== "Missing" && !isErrorLikeText(v))
    .join(" ")
    .toLowerCase()
    .replace(/[^a-z0-9\s&-]/g, " ");

  const unique: string[] = [];
  for (const raw of joined.split(/\s+/)) {
    const token = raw.trim();
    if (!token || token.length < 3 || stop.has(token)) continue;
    if (!unique.includes(token)) unique.push(token);
    if (unique.length >= 7) break;
  }
  return compactSpaces(unique.join(" "));
}

function industrySignalPresent(html: string, industry: string): boolean {
  const t = html.toLowerCase();
  const checks: Record<string, RegExp> = {
    ecommerce: /\b(ecommerce|store|shop|product|cart|checkout|sku)\b/i,
    saas: /\b(saas|software|platform|subscription|free trial|book demo|request demo)\b/i,
    local_service: /\b(service area|near me|book appointment|get quote|call now)\b/i,
    agency: /\b(agency|studio|portfolio|case studies|client work)\b/i,
    media: /\b(news|editorial|breaking|opinion|subscribe)\b/i,
    nonprofit: /\b(nonprofit|donate|volunteer|mission|charity)\b/i,
    manufacturing: /\b(manufacturing|industrial|factory|automation|supply chain)\b/i,
    other: /$^/,
  };
  const re = checks[industry] || checks.other;
  return re.test(t);
}

type ContentIntentTier = "commercial" | "education_community" | "neutral";

function scoreEducationSignals(html: string): number {
  const t = html.toLowerCase();
  const terms = [
    "course",
    "courses",
    "curriculum",
    "workshop",
    "cohort",
    "community",
    "student",
    "students",
    "learn",
    "learning",
    "tutorial",
    "academy",
    "bootcamp",
    "syllabus",
    "certificate",
    "mentor",
    "meetup",
    "scholarship",
  ];
  let score = 0;
  for (const w of terms) {
    if (t.includes(w)) score += 8;
  }
  if (/\b(nonprofit|volunteer|donate)\b/i.test(html)) score += 14;
  return Math.min(100, score);
}

function scoreCommercialSignals(html: string, industry: string): number {
  if (industry === "ecommerce") return 100;
  const t = html.toLowerCase();
  let score = industry === "saas" ? 28 : 0;
  const terms = ["add to cart", "checkout", "buy now", "pricing", "subscribe now", "free trial", "request demo", "book a demo", "get quote"];
  for (const w of terms) {
    if (t.includes(w)) score += 22;
  }
  return Math.min(100, score);
}

function resolveContentIntentTier(html: string, industry: string): {
  tier: ContentIntentTier;
  eduScore: number;
  commercialScore: number;
} {
  const eduScore = scoreEducationSignals(html);
  const commercialScore = scoreCommercialSignals(html, industry);
  if (industry === "nonprofit") {
    return { tier: "education_community", eduScore: Math.max(eduScore, 40), commercialScore };
  }
  if (commercialScore >= 50 && commercialScore >= eduScore + 12) {
    return { tier: "commercial", eduScore, commercialScore };
  }
  if (eduScore >= 24 || industry === "nonprofit") {
    return { tier: "education_community", eduScore, commercialScore };
  }
  return { tier: "neutral", eduScore, commercialScore };
}

function intentClarityForConfidence(eduScore: number, commercialScore: number): number {
  const gap = Math.abs(eduScore - commercialScore);
  return Math.min(100, Math.round(42 + gap * 0.45));
}

function fieldEvidenceQuality(current: string, kind: "title" | "metaDescription" | "h1"): { present: boolean; quality: number } {
  if (!current || current === "Missing") return { present: false, quality: 0 };
  const hasTag = /[<>]/.test(current);
  let quality = 88;
  if (hasTag) quality -= 48;
  const len = current.length;
  if (kind === "title") {
    if (len < 12) quality -= 22;
    if (len > 70) quality -= 12;
  } else if (kind === "metaDescription") {
    if (len < 40) quality -= 18;
    if (len > 320) quality -= 14;
  } else {
    if (len < 6) quality -= 20;
    if (len > 120) quality -= 10;
  }
  return { present: true, quality: Math.max(0, Math.min(100, Math.round(quality))) };
}

function computeContentSuggestionConfidence(input: {
  industryConfidence: number;
  fieldPresent: boolean;
  fieldQuality: number;
  intentClarity: number;
  tierAlignmentBonus: number;
  errorPageDetected?: boolean;
}): number {
  const base =
    input.industryConfidence * 0.28 +
    input.fieldQuality * 0.32 +
    input.intentClarity * 0.28 +
    input.tierAlignmentBonus;
  let v = Math.round(base);
  if (!input.fieldPresent) v -= 14;
  if (input.errorPageDetected) v -= 35;
  return Math.max(0, Math.min(100, v));
}

function scoreFromSignals(base: number, bonuses: number[], penalties: number[]) {
  const value = base + bonuses.reduce((a, b) => a + b, 0) - penalties.reduce((a, b) => a + b, 0);
  return Math.max(0, Math.min(100, Math.round(value)));
}

function count(html: string, regex: RegExp) {
  return (html.match(regex) || []).length;
}

export function analyzeWebsite(htmlRaw: string, pagespeedRaw: any): AuditResult {
  const html = String(htmlRaw || "").toLowerCase();
  const metrics = pagespeedRaw?.lighthouseResult?.audits ?? {};
  const perfScore = pagespeedRaw?.lighthouseResult?.categories?.performance?.score;

  const hasViewport = /<meta[^>]*name=["']viewport["']/i.test(html);
  const formCount = count(html, /<form[\s>]/gi);
  const ctaCount = count(html, /(get started|book demo|contact us|sign up|try free|request demo)/gi);
  const h1Count = count(html, /<h1[\s>]/gi);
  const headings = count(html, /<h[1-6][\s>]/gi);
  const altCount = count(html, /<img[^>]*alt=["'][^"']+/gi);
  const imgCount = count(html, /<img[\s>]/gi);
  const ariaCount = count(html, /\saria-[a-z-]+=/gi);
  const navCount = count(html, /<nav[\s>]/gi);
  const titleTag = /<title>.+<\/title>/i.test(html);
  const metaDesc = /<meta[^>]*name=["']description["'][^>]*>/i.test(html);
  const hasCanonical = /<link[^>]*rel=["']canonical["']/i.test(html);

  const lcp = metrics["largest-contentful-paint"]?.numericValue ?? 3500;
  const cls = metrics["cumulative-layout-shift"]?.numericValue ?? 0.18;
  const tbt = metrics["total-blocking-time"]?.numericValue ?? 280;

  const uiux = scoreFromSignals(
    65,
    [navCount > 0 ? 10 : 0, ctaCount > 0 ? 8 : 0, headings >= 5 ? 8 : 0],
    [h1Count === 0 ? 10 : 0, ctaCount === 0 ? 10 : 0]
  );

  const perf = scoreFromSignals(
    typeof perfScore === "number" ? perfScore * 100 : 55,
    [lcp < 2500 ? 10 : 0, cls < 0.1 ? 8 : 0, tbt < 200 ? 8 : 0],
    [lcp > 4000 ? 12 : 0, cls > 0.25 ? 10 : 0, tbt > 600 ? 10 : 0]
  );

  const mobile = scoreFromSignals(
    60,
    [hasViewport ? 20 : 0, ctaCount > 0 ? 6 : 0],
    [!hasViewport ? 20 : 0, headings < 3 ? 6 : 0]
  );

  const access = scoreFromSignals(
    58,
    [imgCount > 0 ? Math.min(20, Math.round((altCount / imgCount) * 20)) : 12, ariaCount > 2 ? 10 : 0],
    [imgCount > 0 && altCount / imgCount < 0.7 ? 12 : 0]
  );

  const seo = scoreFromSignals(
    62,
    [titleTag ? 12 : 0, metaDesc ? 10 : 0, hasCanonical ? 8 : 0, h1Count === 1 ? 6 : 0],
    [!titleTag ? 15 : 0, !metaDesc ? 12 : 0, h1Count > 1 ? 6 : 0]
  );

  const leads = scoreFromSignals(
    50,
    [formCount > 0 ? 20 : 0, ctaCount > 0 ? 20 : 0],
    [formCount === 0 ? 15 : 0, ctaCount === 0 ? 15 : 0]
  );

  const overall = Math.round(
    uiux * 0.25 + perf * 0.2 + mobile * 0.2 + access * 0.15 + seo * 0.15 + leads * 0.05
  );
  const leadBoost = `${Math.round((100 - overall) * 0.3)}%`;

  const issues: string[] = [];
  const fixes: string[] = [];

  if (!hasViewport) {
    issues.push("Missing mobile viewport meta tag.");
    fixes.push('Add `<meta name="viewport" content="width=device-width, initial-scale=1" />`.');
  }
  if (!titleTag || !metaDesc) {
    issues.push("SEO metadata is incomplete.");
    fixes.push("Add unique title + meta description per primary landing page.");
  }
  if (imgCount > 0 && altCount / imgCount < 0.7) {
    issues.push("Many images are missing descriptive alt text.");
    fixes.push("Provide meaningful alt text for all informative images.");
  }
  if (lcp > 4000 || tbt > 600) {
    issues.push("Performance metrics indicate heavy render workload.");
    fixes.push("Compress hero media, defer non-critical JS, and inline critical CSS.");
  }
  if (formCount === 0) {
    issues.push("No lead capture form found.");
    fixes.push("Add above-the-fold lead form with 1 primary CTA.");
  }
  if (ctaCount === 0) {
    issues.push("No clear conversion CTA detected.");
    fixes.push('Add repeated CTA labels like "Book Demo" and "Start Free Trial".');
  }
  if (h1Count !== 1) {
    issues.push("Heading hierarchy is weak (expect exactly one H1).");
    fixes.push("Use one descriptive H1 and structured H2/H3 sections.");
  }

  const competitorsAvg = Math.max(35, Math.min(95, overall - 8 + (overall % 13)));

  return {
    scores: { uiux, perf, mobile, access, seo, leads, overall },
    issues,
    fixes,
    leadBoost,
    benchmark: { you: overall, competitorsAvg },
    promptsUsed: AUDIT_PROMPTS,
    colorSuggestions: COLOR_PSYCHOLOGY_TIPS,
  };
}

export function generateContentSuggestions(htmlRaw: string, industry: string, industryConfidence: number): ContentSuggestion[] {
  const html = String(htmlRaw || "");
  const titleMatch = html.match(/<title[^>]*>([\s\S]*?)<\/title>/i);
  const h1Match = html.match(/<h1[^>]*>([\s\S]*?)<\/h1>/i);
  const metaMatch = html.match(/<meta[^>]*name=["']description["'][^>]*content=["']([^"']*)["'][^>]*>/i);

  const extractedTitle = normalizeContentField(stripHtmlForContentPreview(titleMatch?.[1] || ""));
  const extractedH1 = normalizeContentField(stripHtmlForContentPreview(h1Match?.[1] || ""));
  const extractedMeta = normalizeContentField(stripHtmlForContentPreview(metaMatch?.[1] || ""));

  const errorPageDetected =
    isLikelyErrorPage(html) ||
    [extractedTitle, extractedH1, extractedMeta].some((v) => isErrorLikeText(v));

  const currentTitle = sanitizeCurrentField(extractedTitle);
  const currentH1 = sanitizeCurrentField(extractedH1);
  const currentMeta = sanitizeCurrentField(extractedMeta);
  const displayTitle = errorPageDetected ? "Missing" : currentTitle;
  const displayH1 = errorPageDetected ? "Missing" : currentH1;
  const displayMeta = errorPageDetected ? "Missing" : currentMeta;

  const { tier, eduScore, commercialScore } = resolveContentIntentTier(html, industry);
  const intentClarity = intentClarityForConfidence(eduScore, commercialScore);
  const brand = extractBrandHint(displayTitle) || extractBrandHint(displayH1);
  const topicPhrase = buildTopicPhrase([displayH1, displayTitle, displayMeta]);
  const useIndustryInCopy =
    industryConfidence >= 72 &&
    industry !== "other" &&
    tier === "commercial" &&
    industrySignalPresent(`${displayTitle} ${displayH1} ${displayMeta} ${html.slice(0, 3000)}`, industry);

  const guidelinesCommercial = useIndustryInCopy
    ? [`Align headline with ${industry} buyer intent.`, "Use specific outcomes and credibility cues.", "Keep metadata human-readable and concise."]
    : ["Lead with a clear offer and who it serves.", "Add a concrete next step (trial, demo, purchase).", "Avoid vague superlatives; prefer proof or specificity."];

  const guidelinesEducation = [
    "Lead with learning outcomes, community value, or mission.",
    "Keep tone welcoming; avoid hard-sell or revenue framing.",
    "Meta: who it’s for, what they can explore, and one clear next step.",
  ];

  const guidelinesNeutral = [
    "State the page topic and audience in plain language.",
    "Keep title and H1 closely aligned.",
    "Meta description: value + audience + one next step (about 150–160 characters).",
  ];

  const guidelinesError = [
    "This result likely came from a blocked/error page, not your intended content.",
    "Verify URL, access permissions, and anti-bot/CDN settings, then rerun.",
    "Use title/meta/H1 suggestions only after a successful live fetch.",
  ];

  let titlePack: { suggested: string; reason: string; alignment: number };
  let metaPack: { suggested: string; reason: string; alignment: number };
  let h1Pack: { suggested: string; reason: string; alignment: number };

  if (errorPageDetected) {
    titlePack = {
      suggested: "Page unavailable during scan - verify access and retry",
      reason: "The fetched content appears to be an error/blocked page, so content recommendations are conservative until a valid page is scanned.",
      alignment: 2,
    };
    metaPack = {
      suggested:
        "We could not read a valid page description from this URL. Check URL accuracy, access controls, and CDN/firewall rules, then rerun the audit.",
      reason: "Meta suggestion switched to recovery guidance because source content was error-like.",
      alignment: 2,
    };
    h1Pack = {
      suggested: "This page could not be audited right now",
      reason: "H1 recommendation avoids reusing error text and focuses on retry guidance.",
      alignment: 2,
    };
  } else if (tier === "education_community") {
    const head = brand ? `${brand} — ` : "";
    titlePack = {
      suggested: `${head}Courses, workshops, and community learning`,
      reason: `Education/community signals in page copy (score ${eduScore}) — suggestions emphasize learning and participation, not sales funnels.`,
      alignment: 12,
    };
    metaPack = {
      suggested:
        "Explore programs, workshops, and ways to connect. See what you can learn, who it’s for, and how to get started.",
      reason: "Meta tuned for learning and community discovery based on detected page intent.",
      alignment: 12,
    };
    h1Pack = {
      suggested: brand ? `${brand}: learn and connect` : "Welcome — explore courses, workshops, and community",
      reason: "H1 focuses on participation and clarity for education- or community-oriented visitors.",
      alignment: 12,
    };
  } else if (tier === "commercial") {
    const readableTopic = topicPhrase || (brand ? brand.toLowerCase() : "your website");
    const cleanTopic = trimWords(readableTopic, 7);
    const start = brand ? `${brand} | ` : "";
    const commercialTitleCore = useIndustryInCopy
      ? `${toSentenceCase(cleanTopic)} for ${industry.replace(/_/g, " ")} growth`
      : `${toSentenceCase(cleanTopic)} with faster, clearer conversion flow`;
    const commercialMetaCore = useIndustryInCopy
      ? `Live audit insights for your ${industry.replace(/_/g, " ")} presence: improve speed, SEO, trust signals, and conversion with clear next actions.`
      : `Live audit insights for ${cleanTopic}: improve speed, SEO, trust signals, and conversion with clear next actions.`;
    const h1Base = currentH1 !== "Missing" ? trimWords(currentH1, 8) : toSentenceCase(trimWords(cleanTopic, 8));

    if (useIndustryInCopy) {
      titlePack = {
        suggested: trimChars(`${start}${commercialTitleCore}`, 68),
        reason: `Commercial signals (score ${commercialScore}) and confident industry match (${industry}) support outcome-oriented copy.`,
        alignment: 14,
      };
      metaPack = {
        suggested: trimChars(commercialMetaCore, 170),
        reason: "Description matches detected commercial intent and industry category.",
        alignment: 14,
      };
      h1Pack = {
        suggested: trimChars(`${h1Base} with a clearer, faster experience`, 95),
        reason: "H1 emphasizes measurable outcomes aligned with commercial page signals.",
        alignment: 14,
      };
    } else {
      titlePack = {
        suggested: trimChars(`${start}${toSentenceCase(commercialTitleCore)}`, 68),
        reason: `Commercial cues present (score ${commercialScore}) but industry fit is uncertain — copy stays specific without naming the wrong market.`,
        alignment: 10,
      };
      metaPack = {
        suggested: trimChars(commercialMetaCore, 170),
        reason: "Safe commercial-leaning meta without assuming a narrow industry label.",
        alignment: 10,
      };
      h1Pack = {
        suggested: trimChars(`${h1Base} with clearer value and a stronger next step`, 95),
        reason: "H1 guidance stays conversion-aware but avoids incorrect vertical language.",
        alignment: 10,
      };
    }
  } else {
    titlePack = {
      suggested: brand
        ? `${brand} — what we offer and how to get involved`
        : "Clear site focus: what visitors find here and who it’s for",
      reason: `Neutral intent (education ${eduScore}, commercial ${commercialScore}) — copy avoids aggressive sales language.`,
      alignment: 8,
    };
    metaPack = {
      suggested:
        "Describe what this site or page provides, who benefits, and the simplest next step — without sounding like a sales pitch.",
      reason: "Balanced meta for pages without strong commercial or learning signals.",
      alignment: 8,
    };
    h1Pack = {
      suggested: brand ? `${brand} — welcome` : "A simple, accurate headline for this page",
      reason: "H1 stays informational and welcoming when page intent is mixed or unclear.",
      alignment: 8,
    };
  }

  const gTitle = fieldEvidenceQuality(displayTitle, "title");
  const gMeta = fieldEvidenceQuality(displayMeta, "metaDescription");
  const gH1 = fieldEvidenceQuality(displayH1, "h1");

  const confTitle = computeContentSuggestionConfidence({
    industryConfidence,
    fieldPresent: gTitle.present,
    fieldQuality: gTitle.quality,
    intentClarity,
    tierAlignmentBonus: titlePack.alignment,
    errorPageDetected,
  });
  const confMeta = computeContentSuggestionConfidence({
    industryConfidence,
    fieldPresent: gMeta.present,
    fieldQuality: gMeta.quality,
    intentClarity,
    tierAlignmentBonus: metaPack.alignment,
    errorPageDetected,
  });
  const confH1 = computeContentSuggestionConfidence({
    industryConfidence,
    fieldPresent: gH1.present,
    fieldQuality: gH1.quality,
    intentClarity,
    tierAlignmentBonus: h1Pack.alignment,
    errorPageDetected,
  });

  const bullets = errorPageDetected
    ? guidelinesError
    : tier === "education_community"
      ? guidelinesEducation
      : tier === "commercial"
        ? guidelinesCommercial
        : guidelinesNeutral;

  return [
    {
      type: "title",
      current: displayTitle,
      suggested: titlePack.suggested,
      reason: titlePack.reason,
      confidence: confTitle,
      guidelineBullets: bullets,
    },
    {
      type: "metaDescription",
      current: displayMeta,
      suggested: metaPack.suggested,
      reason: metaPack.reason,
      confidence: confMeta,
      guidelineBullets: bullets,
    },
    {
      type: "h1",
      current: displayH1,
      suggested: h1Pack.suggested,
      reason: h1Pack.reason,
      confidence: confH1,
      guidelineBullets: bullets,
    },
  ];
}
