import { chromium, devices } from "playwright";
import AxeBuilder from "@axe-core/playwright";
import * as cheerio from "cheerio";
import { existsSync } from "node:fs";
import * as path from "node:path";
import { execFile } from "node:child_process";
import { promisify } from "node:util";
import { generateContentSuggestions } from "./audit-engine";
import { generatePerfectAuditInsights } from "./ai";
import { getCVScore } from "./cv-client";
import { analyzeLeadGen } from "./leadgen";
import type { LeadGenResult } from "./leadgen";
import { INDUSTRY_BENCHMARKS } from "./benchmarks";
import { detectIndustry, isEcommerceStorefrontHint } from "./industry";
import { detectStructuralIssues } from "./issue-detection";
import { captureScreenshots } from "./screenshot";
import { computeTrendsSummary } from "./trends";
import { computeScores, prioritizeRecommendations, DETERMINISTIC_SCORES_TRUST_SOURCE } from "./scoring";
import { makeTrustMeta } from "./trust";
import { env } from "./env";
import { analyzeUIUX } from "./ux-rules";
import type { AuditReport, Issue, StageTraceEntry, TrustMeta } from "./audit-types";

const execFileAsync = promisify(execFile);
const PLAYWRIGHT_DESKTOP_TIMEOUT_MS = 12000;
const AXE_TIMEOUT_MS = 4000;
const MOBILE_TIMEOUT_MS = 4500;
const SCREENSHOT_TIMEOUT_MS = 14000;
const LIGHTHOUSE_TIMEOUT_MS = 20000;
const HTML_FETCH_TIMEOUT_MS = 9000;
const PIPELINE_BUDGET_MS = 30000;

function normalizeUrl(input: string) {
  const trimmed = input.trim();
  if (!trimmed) return "";
  return /^https?:\/\//i.test(trimmed) ? trimmed : `https://${trimmed}`;
}

function failIssue(category: Issue["category"], title: string, detail: string, severity: Issue["severity"]): Issue {
  return { category, title, detail, severity };
}

export function detectBlockedResponseFromHtml(html: string): boolean {
  const plain = String(html || "")
    .replace(/<script[\s\S]*?<\/script>/gi, " ")
    .replace(/<style[\s\S]*?<\/style>/gi, " ")
    .replace(/<[^>]+>/g, " ")
    .replace(/\s+/g, " ")
    .trim()
    .toLowerCase();

  const signals = [
    "request could not be satisfied",
    "generated by cloudfront",
    "access denied",
    "forbidden",
    "not found",
    "service unavailable",
    "temporarily unavailable",
    "degraded-fallback",
  ];
  const signalCount = signals.reduce((acc, signal) => acc + (plain.includes(signal) ? 1 : 0), 0);
  const hasStatusErrorSignal = /\b(403|404|429|500|502|503)\b\s*(error|forbidden|not found|bad gateway|service unavailable)?/i.test(plain);

  return signalCount >= 2 || (signalCount >= 1 && hasStatusErrorSignal);
}

function formatAxeFailureDetail(error: unknown): string {
  const message = error instanceof Error ? error.message : "unknown error";
  // Keep stack-level internals out of end-user recommendations.
  if (/module is not defined|page\.evaluate|execution context|csp|content security/i.test(message)) {
    return "Accessibility checks were limited by runtime/script restrictions on this page. Re-run scan or test with a less restricted environment.";
  }
  return "Accessibility checks were partially unavailable for this run.";
}

export async function runAuditPipeline(
  rawUrl: string,
  options: { includeAi?: boolean } = {}
): Promise<
  Omit<AuditReport, "competitors" | "analytics" | "roi" | "roiReason" | "isLive" | "status" | "liveTimestamp" | "auditId" | "history"> & {
    trustByField: Record<string, TrustMeta>;
    scanBlockedOrDegraded: boolean;
  }
> {
  const pipelineStartedAt = Date.now();
  const url = normalizeUrl(rawUrl);
  if (!url) throw new Error("Invalid URL.");

  let parsed: URL;
  try {
    parsed = new URL(url);
  } catch {
    throw new Error("Invalid URL.");
  }
  if (!["http:", "https:"].includes(parsed.protocol)) throw new Error("Invalid URL.");

  const pipeline: string[] = ["validate-url"];
  const stageTrace: StageTraceEntry[] = [];
  const issues: Issue[] = [];

  let desktopHtml = "";
  let mobileHtml = "";
  let mobileTapTargets = 0;
  let playwrightFailed = false;
  let lighthouseFailed = false;
  let uxScore = 100;
  let uxIssuesCount = 0;
  let leadGenResult: LeadGenResult | null = null;
  let deviceResults: Array<{ device: string; tapTargetsOk: boolean; smallTargets: number }> = [];
  const fastLighthouseMode = options.includeAi === false;

  let playwrightResult: PromiseSettledResult<void> = {
    status: "rejected",
    reason: new Error("playwright not executed"),
  };
  let screenshotResult: PromiseSettledResult<{ desktop?: string; mobile?: string } | undefined> = {
    status: "fulfilled",
    value: undefined,
  };
  let lighthouseResult: PromiseSettledResult<{ categories?: Record<string, { score: number }> }> = {
    status: "rejected",
    reason: new Error("lighthouse not executed"),
  };

  if (fastLighthouseMode) {
    pipeline.push("fast-lighthouse-priority");
    const [lhRes, htmlRes, fastScreenshotRes] = await Promise.allSettled([
      runStageTrace(stageTrace, "lighthouse", async () =>
        withTimeout(async () => {
          pipeline.push("lighthouse");
          return await runLighthouseCli(url);
        }, Math.min(LIGHTHOUSE_TIMEOUT_MS, Math.max(2500, PIPELINE_BUDGET_MS - (Date.now() - pipelineStartedAt))), "lighthouse")
      ),
      runStageTrace(stageTrace, "http-html", async () =>
        withTimeout(async () => await fetchHtmlFallback(url), HTML_FETCH_TIMEOUT_MS, "http-html")
      ),
      runStageTrace(stageTrace, "screenshot", async () =>
        withTimeout(async () => {
          pipeline.push("puppeteer-screenshot-fast");
          return await captureScreenshots(url, {
            navTimeoutMs: 6000,
            settleMs: 500,
            includeMobile: false,
          });
        }, Math.min(SCREENSHOT_TIMEOUT_MS, 12000), "screenshot")
      ),
    ]);

    lighthouseResult = lhRes;
    if (htmlRes.status === "fulfilled") {
      desktopHtml = htmlRes.value;
      mobileHtml = htmlRes.value;
    }
    screenshotResult = fastScreenshotRes;
    playwrightResult = { status: "rejected", reason: new Error("playwright skipped in fast mode") };
  } else {
    [playwrightResult, screenshotResult, lighthouseResult] = await Promise.allSettled([
      runStageTrace(stageTrace, "playwright", async () =>
        withTimeout(async () => {
        const browser = await chromium.launch({ headless: true });
        try {
          const desktopCtx = await browser.newContext();
          pipeline.push("playwright-desktop");
          const page = await desktopCtx.newPage();
          await page.goto(url, { waitUntil: "domcontentloaded", timeout: PLAYWRIGHT_DESKTOP_TIMEOUT_MS });
          desktopHtml = await page.content();

          const uxResult = await analyzeUIUX(desktopHtml, page);
          uxScore = uxResult.uxScore;
          uxIssuesCount = uxResult.issues.length;
          uxResult.issues.forEach(msg => {
            issues.push(failIssue("uiux", "Manual UX Heuristic", msg, "medium"));
          });

          pipeline.push("axe-accessibility");
          try {
            const axe = await withTimeout(async () => await new AxeBuilder({ page }).analyze(), AXE_TIMEOUT_MS, "axe");
            const axeViolations = axe.violations.length;
            if (axeViolations > 0) {
              issues.push(
                failIssue(
                  "accessibility",
                  "Accessibility violations detected",
                  `axe-core reported ${axeViolations} violation group(s).`,
                  axeViolations > 10 ? "high" : axeViolations > 3 ? "medium" : "low"
                )
              );
            }
          } catch (error) {
            console.warn("[audit:axe:partial-unavailable]", error instanceof Error ? error.message : String(error));
            issues.push(
              failIssue(
                "accessibility",
                "Accessibility scan partially unavailable",
                formatAxeFailureDetail(error),
                "low"
              )
            );
          }

          pipeline.push("playwright-mobile");

          // Multi-device tap target checks
          pipeline.push("multi-device-checks");
          const mobileDevices = [
            { name: "Desktop 1440", descriptor: { viewport: { width: 1440, height: 900 }, userAgent: "" } },
            { name: "iPhone 14",    descriptor: devices["iPhone 14"] },
            { name: "Galaxy S23",   descriptor: devices["Galaxy S23"] ?? devices["Pixel 5"] },
          ] as const;

          for (const d of mobileDevices) {
            try {
              const dCtx = await browser.newContext(d.descriptor as Parameters<typeof browser.newContext>[0]);
              const dPage = await dCtx.newPage();
              await dPage.goto(url, { waitUntil: "domcontentloaded", timeout: MOBILE_TIMEOUT_MS });
              const tapTargetEls = dPage.locator("a,button,input[type='button'],input[type='submit']");
              const total = await tapTargetEls.count();
              // Count small tap targets (bounding box < 44×44 px — WCAG 2.5.5)
              let smallTargets = 0;
              for (let i = 0; i < Math.min(total, 30); i++) {
                try {
                  const box = await tapTargetEls.nth(i).boundingBox();
                  if (box && (box.width < 44 || box.height < 44)) smallTargets++;
                } catch { /* skip unmeasurable */ }
              }
              const tapTargetsOk = total >= 3 && smallTargets === 0;
              deviceResults.push({ device: d.name, tapTargetsOk, smallTargets });
              if (!tapTargetsOk && d.name !== "Desktop 1440") {
                issues.push(
                  failIssue("mobile", `Small tap targets on ${d.name}`,
                    `${smallTargets} element(s) smaller than 44×44px detected.`, "medium")
                );
              }
              if (d.name === "iPhone 14") {
                mobileHtml = await dPage.content();
                mobileTapTargets = total;
              }
              await dCtx.close();
            } catch (devErr) {
              console.warn(`[audit:device:${d.name}]`, devErr instanceof Error ? devErr.message : String(devErr));
            }
          }

          // Lead Gen analysis (with live page access for above-fold CTA check)
          pipeline.push("leadgen-analysis");
          const mobileCtx2 = await browser.newContext({ ...devices["iPhone 13"] });
          const leadPage = await mobileCtx2.newPage();
          await leadPage.goto(url, { waitUntil: "domcontentloaded", timeout: MOBILE_TIMEOUT_MS });
          leadGenResult = await analyzeLeadGen({ html: desktopHtml }, leadPage);
          console.log(
            "[leadgen:evidence]",
            JSON.stringify({
              url,
              hasContactForm: leadGenResult.hasContactForm,
              contactFormConfidence: leadGenResult.contactFormConfidence,
              contactFormEvidence: leadGenResult.contactFormEvidence?.slice(0, 5),
            })
          );
          leadGenResult.issues.forEach(msg => {
            issues.push(failIssue("leadConversion", "Lead Gen Heuristic", msg, "medium"));
          });
          await mobileCtx2.close();

          await desktopCtx.close();
        } finally {
          await browser.close();
        }
        }, Math.min(PLAYWRIGHT_DESKTOP_TIMEOUT_MS + AXE_TIMEOUT_MS + MOBILE_TIMEOUT_MS, Math.max(2500, PIPELINE_BUDGET_MS - (Date.now() - pipelineStartedAt))), "playwright")
      ),
      runStageTrace(stageTrace, "screenshot", async () => {
        pipeline.push("puppeteer-screenshot");
        return await captureScreenshots(url);
      }),
      runStageTrace(stageTrace, "lighthouse", async () => withTimeout(async () => {
        pipeline.push("lighthouse");
        return await runLighthouseCli(url);
      }, Math.min(LIGHTHOUSE_TIMEOUT_MS, Math.max(2500, PIPELINE_BUDGET_MS - (Date.now() - pipelineStartedAt))), "lighthouse")),
    ]);
  }

  if (playwrightResult.status === "rejected" && !fastLighthouseMode) {
    playwrightFailed = true;
    issues.push(
      failIssue(
        "uiux",
        "Playwright rendered scan failed",
        "Rendered browser scan failed; attempting live HTML fallback extraction.",
        "medium"
      )
    );

    const htmlFallback = await runStageTrace(stageTrace, "http-html", async () =>
      await withTimeout(async () => await fetchHtmlFallback(url), HTML_FETCH_TIMEOUT_MS, "http-html")
    ).catch((error) => {
      throw withTrace(error, stageTrace);
    });

    desktopHtml = htmlFallback;
    mobileHtml = htmlFallback;
    mobileTapTargets = 0;

    // Fallback HTML-only lead gen analysis
    leadGenResult = await analyzeLeadGen({ html: htmlFallback });
    console.log(
      "[leadgen:evidence]",
      JSON.stringify({
        url,
        hasContactForm: leadGenResult.hasContactForm,
        contactFormConfidence: leadGenResult.contactFormConfidence,
        contactFormEvidence: leadGenResult.contactFormEvidence?.slice(0, 5),
      })
    );
    leadGenResult.issues.forEach(msg => {
      issues.push(failIssue("leadConversion", "Lead Gen Heuristic", msg, "medium"));
    });
  }

  if (!desktopHtml) {
    const htmlFallback = await runStageTrace(stageTrace, "http-html", async () =>
      await withTimeout(async () => await fetchHtmlFallback(url), HTML_FETCH_TIMEOUT_MS, "http-html")
    ).catch((error) => {
      throw withTrace(error, stageTrace);
    });
    desktopHtml = htmlFallback;
    mobileHtml = htmlFallback;
  }

  if (screenshotResult.status === "rejected") {
    issues.push(
      failIssue(
        "uiux",
        "Screenshot capture failed",
        "Puppeteer screenshot failed; continuing without screenshots.",
        "low"
      )
    );
  }

  if (lighthouseResult.status === "rejected") {
    lighthouseFailed = true;
    issues.push(
      failIssue(
        "performance",
        "Lighthouse scan failed",
        "Lighthouse metrics unavailable for this run; performance/SEO/accessibility may be conservative.",
        "medium"
      )
    );
  }

  if (!desktopHtml && lighthouseFailed) {
    issues.push(
      failIssue(
        "uiux",
        "Severe network/runtime restrictions",
        "Primary render and Lighthouse failed. Returning a degraded report from minimal fallback signals.",
        "high"
      )
    );
    desktopHtml = `<html><head><title>${escapeHtml(url)}</title></head><body><main>degraded-fallback</main></body></html>`;
    mobileHtml = desktopHtml;
    pipeline.push("degraded-fallback");
  }

  const screenshots = screenshotResult.status === "fulfilled" ? screenshotResult.value : undefined;
  
  // In fast mode, try to extract screenshots from Lighthouse output if available
  let enhancedScreenshots = screenshots;
  if (fastLighthouseMode && lighthouseResult.status === "fulfilled" && !screenshots) {
    const lhScreenshot = (lighthouseResult.value as any)?.audits?.["full-page-screenshot"]?.details?.screenshot?.data;
    if (lhScreenshot) {
      enhancedScreenshots = { desktop: `data:image/webp;base64,${lhScreenshot}` };
    }
  }
  
  const screenshot = enhancedScreenshots?.desktop;

  const $ = cheerio.load(desktopHtml || "<html></html>");
  const m$ = cheerio.load(mobileHtml || desktopHtml || "<html></html>");
  const h1Count = $("h1").length;
  const titlePresent = $("title").text().trim().length > 0;
  const metaDescriptionPresent = $('meta[name="description"]').length > 0;
  const hasViewport = m$('meta[name="viewport"]').length > 0;
  const titleText = $("title").text().trim();
  const metaText = $('meta[name="description"]').attr("content")?.trim() || "";
  const formCount = $("form").length;
  const imgCount = $("img").length;
  const altCount = $("img[alt]").length;
  const wordCount = $("body").text().replace(/\s+/g, " ").trim().split(" ").filter(Boolean).length;
  const ctaCount = $("a,button,input[type='submit']")
    .filter((_, el) => {
      const text = $(el).text().toLowerCase().trim();
      const value = ($(el).attr("value") || "").toLowerCase();
      return /(book|demo|start|get|contact|free|trial|audit)/.test(`${text} ${value}`);
    })
    .length;
  const mobileTapTargetsOk = !playwrightFailed && mobileTapTargets >= 3;

  const industryHint = detectIndustry(desktopHtml || mobileHtml);
  const isEcommerce =
    industryHint.category === "ecommerce" || isEcommerceStorefrontHint(desktopHtml || mobileHtml || "", url);
  const scriptCount = $("script").length;
  const domNodeCount = $("*").length;
  const blockedResponseDetected = detectBlockedResponseFromHtml(desktopHtml || mobileHtml || "");
  if (blockedResponseDetected) {
    pipeline.push("blocked-response-detected");
    issues.push(
      failIssue(
        "uiux",
        "Target page appears blocked or unavailable",
        "The fetched response looked like an error/blocked page (for example CDN/firewall or permission restrictions). Verify URL access and rerun from an allowlisted environment.",
        "high"
      )
    );
  } else {
    issues.push(
      ...detectStructuralIssues({
        titlePresent,
        metaDescriptionPresent,
        h1Count,
        hasViewport,
        mobileTapTargetsOk,
        formCount,
        ctaCount,
        scriptCount,
        domNodeCount,
        isEcommerce,
      })
    );
  }

  const effectiveHasViewport = blockedResponseDetected ? false : hasViewport;
  const effectiveMobileTapTargetsOk = blockedResponseDetected ? false : mobileTapTargetsOk;
  const effectiveH1Count = blockedResponseDetected ? 0 : h1Count;
  const effectiveTitlePresent = blockedResponseDetected ? false : titlePresent;
  const effectiveMetaDescriptionPresent = blockedResponseDetected ? false : metaDescriptionPresent;
  const effectiveFormCount = blockedResponseDetected ? 0 : formCount;
  const effectiveCtaCount = blockedResponseDetected ? 0 : ctaCount;
  const effectiveIsEcommerce = blockedResponseDetected ? false : isEcommerce;

  const customPerformanceSignal = Math.min(
    100,
    Math.max(0, 60 + (effectiveHasViewport ? 10 : 0) + (effectiveMobileTapTargetsOk ? 10 : 0) + (effectiveCtaCount > 0 ? 10 : 0) + (effectiveFormCount > 0 ? 10 : 0))
  );

  let lighthousePerformance = Math.round(
    ((lighthouseResult.status === "fulfilled" ? lighthouseResult.value?.categories?.performance?.score : 0) ?? 0) * 100
  );
  let lighthouseSeo = Math.round(
    ((lighthouseResult.status === "fulfilled" ? lighthouseResult.value?.categories?.seo?.score : 0) ?? 0) * 100
  );
  let lighthouseAccessibility = Math.round(
    ((lighthouseResult.status === "fulfilled" ? lighthouseResult.value?.categories?.accessibility?.score : 0) ?? 0) * 100
  );
  const lighthouseBestPractices = Math.round(
    ((lighthouseResult.status === "fulfilled" ? lighthouseResult.value?.categories?.["best-practices"]?.score : 0) ?? 0) * 100
  );

  if (lighthouseResult.status !== "fulfilled") {
    lighthousePerformance = estimatePerformanceFallback({
      blockedResponseDetected,
      hasViewport: effectiveHasViewport,
      scriptCount,
      domNodeCount,
      customPerformanceSignal,
    });
    lighthouseSeo = estimateSeoFallback({
      blockedResponseDetected,
      titlePresent: effectiveTitlePresent,
      metaDescriptionPresent: effectiveMetaDescriptionPresent,
      h1Count: effectiveH1Count,
      wordCount,
    });
    lighthouseAccessibility = estimateAccessibilityFallback({
      blockedResponseDetected,
      imgCount,
      altCount,
      axeIssueCount: issues.filter((i) => i.category === "accessibility").length,
    });
  }

  const scores = computeScores({
    lighthousePerformance,
    lighthouseSeo,
    lighthouseAccessibility,
    lighthouseBestPractices,
    lighthouseAvailable: lighthouseResult.status === "fulfilled",
    hasViewport: effectiveHasViewport,
    mobileTapTargetsOk: effectiveMobileTapTargetsOk,
    h1Count: effectiveH1Count,
    titlePresent: effectiveTitlePresent,
    metaDescriptionPresent: effectiveMetaDescriptionPresent,
    formCount: effectiveFormCount,
    ctaCount: effectiveCtaCount,
    ecommerceHint: effectiveIsEcommerce,
    customPerformanceSignal,
  });

  const recommendations = prioritizeRecommendations(issues).sort((a, b) => {
    const rank = { high: 3, medium: 2, low: 1 };
    return rank[b.priority] - rank[a.priority];
  });

  pipeline.push("report-assembly");
  const detectedIndustry = industryHint;
  const contentFixes = generateContentSuggestions(desktopHtml || mobileHtml, detectedIndustry.category, detectedIndustry.confidence);
  const trends = [{ date: new Date().toISOString(), overall: scores.overall }];
  const trendsSummary = computeTrendsSummary(trends);

  let aiInsights;
  let cvResult;
  let aiStatus: "ok" | "failed" | "skipped" = "skipped";
  let cvStatus: "ok" | "failed" | "skipped" = "skipped";
  if (options.includeAi !== false) {
    const rawData = {
      lighthouse: {
        performance: lighthousePerformance / 100,
        seo: lighthouseSeo / 100,
        accessibility: lighthouseAccessibility / 100,
      },
      axe: { violations: issues.filter((i) => i.category === "accessibility").length },
      html: (desktopHtml || mobileHtml).slice(0, 50000), // Safety cut
      screenshots: enhancedScreenshots,
      url,
      issues,
      leadData: leadGenResult,
    };

    // Run AI and optional CV independently so one failure does not block the other.
    const [aiSettled, cvSettled] = await Promise.allSettled([
      runStageTrace(stageTrace, "ai", async () => await withTimeout(async () => await generatePerfectAuditInsights(rawData), 8000, "ai")),
      runStageTrace(stageTrace, "cv-analysis", async () => await withTimeout(async () => await getCVScore(screenshot), 8000, "cv-analysis"))
    ]);

    if (aiSettled.status === "fulfilled") {
      aiInsights = { ...aiSettled.value, source: "model" as const };
      aiStatus = "ok";
      pipeline.push("ai:groq");
    } else {
      aiStatus = "failed";
      console.warn("[audit:ai:failed]", aiSettled.reason instanceof Error ? aiSettled.reason.message : String(aiSettled.reason));
    }

    if (cvSettled.status === "fulfilled") {
      cvResult = cvSettled.value;
      cvStatus = cvResult ? "ok" : "failed";
      if (cvResult) pipeline.push("ai:cv-cv2");
    } else {
      cvStatus = "failed";
      console.warn("[audit:cv:failed]", cvSettled.reason instanceof Error ? cvSettled.reason.message : String(cvSettled.reason));
    }
  }

  // Keep deterministic scores immutable: AI/CV are advisory only.

  pipeline.push("summary");

  const degraded = pipeline.includes("degraded-fallback");
  const axePartialFailure = issues.some(
    (i) => i.category === "accessibility" && /partially unavailable|limited/i.test(`${i.title} ${i.detail}`)
  );
  const lighthouseOk = lighthouseResult.status === "fulfilled";
  const screenshotOk = Boolean(enhancedScreenshots?.desktop || enhancedScreenshots?.mobile);
  const scanBlockedOrDegraded =
    Boolean(blockedResponseDetected) || degraded || (playwrightFailed && lighthouseFailed);

  const trustByField: Record<string, TrustMeta> = {};

  const renderLevel = degraded || blockedResponseDetected ? "FALLBACK" : playwrightFailed ? "FALLBACK" : "VERIFIED";
  const renderConf = degraded ? 0.24 : blockedResponseDetected ? 0.28 : playwrightFailed ? 0.34 : 0.96;
  trustByField.live_render = makeTrustMeta(
    { playwrightFailed },
    renderLevel,
    playwrightFailed ? "HTTP HTML fetch (Playwright render unavailable)" : "Playwright Chromium desktop + mobile render",
    renderConf
  );

  trustByField.lighthouse = makeTrustMeta(
    { completed: lighthouseOk },
    lighthouseOk ? "VERIFIED" : "FALLBACK",
    "Lighthouse CLI (performance, SEO, accessibility categories)",
    lighthouseOk ? 0.96 : 0.32
  );

  trustByField.axe_accessibility = makeTrustMeta(
    { partialScan: axePartialFailure },
    playwrightFailed || blockedResponseDetected ? "FALLBACK" : "VERIFIED",
    "@axe-core/playwright in rendered page context",
    playwrightFailed || blockedResponseDetected ? 0.3 : axePartialFailure ? 0.9 : 0.94
  );

  trustByField.dom_parsing = makeTrustMeta(
    { cheerio: true },
    blockedResponseDetected || degraded ? "FALLBACK" : "VERIFIED",
    "Cheerio DOM extraction (metadata, headings, forms, CTAs)",
    blockedResponseDetected || degraded ? 0.28 : 0.93
  );

  let scoreHint = 0.94;
  let scoreLevel: TrustMeta["trustLevel"] = "VERIFIED";
  if (blockedResponseDetected || degraded) {
    scoreLevel = "FALLBACK";
    scoreHint = 0.3;
  } else if (playwrightFailed) {
    scoreHint = 0.78;
  } else if (!lighthouseOk) {
    scoreHint = 0.86;
  }
  trustByField.deterministic_scores = makeTrustMeta(scores, scoreLevel, DETERMINISTIC_SCORES_TRUST_SOURCE, scoreHint);

  trustByField.screenshots = makeTrustMeta(
    { desktop: Boolean(enhancedScreenshots?.desktop), mobile: Boolean(enhancedScreenshots?.mobile) },
    screenshotOk ? "VERIFIED" : "FALLBACK",
    fastLighthouseMode && enhancedScreenshots?.desktop && !screenshots?.desktop ? "Lighthouse mobile screenshot" : "Puppeteer viewport screenshot capture",
    screenshotOk ? 0.93 : 0.32
  );

  trustByField.content_suggestions = makeTrustMeta(
    contentFixes,
    "INFERRED",
    "Rule-based content suggestions (audit-engine)",
    0.58
  );

  trustByField.trends_summary = makeTrustMeta(
    trendsSummary,
    "ESTIMATED",
    "Single-audit snapshot baseline (trends.ts)",
    0.66
  );

  if (aiInsights) {
    trustByField.ai_insights = makeTrustMeta(aiInsights, "INFERRED", `Groq ${env.GROQ_MODEL} structured JSON`, 0.62);
  }

  if (cvResult) {
    trustByField.cv_analysis = makeTrustMeta(cvResult, "VERIFIED", "OpenCV pixel-level heuristics (Microservice)", 0.88);
  }

  return {
    url,
    scores,
    issues,
    recommendations,
    detectedIndustry,
    contentFixes,
    trends,
    trendsSummary,
    aiInsights,
    quick_wins: aiInsights?.quick_wins,
    cvBreakdown: cvResult?.cv_breakdown,
    hasCv: !!cvResult,
    aiStatus,
    cvStatus,
    trustByField,
    scanBlockedOrDegraded,
    disclaimers: [
      "Live-only mode: all values come from real-time scans.",
      ...(blockedResponseDetected
        ? ["Blocked/errored target response detected; recommendations are limited until a successful fetch is available."]
        : []),
    ],
    summary: aiInsights?.issues?.[0]?.fix || "AI summary unavailable",
    deterministicNotes: ["Scores are deterministic from live tooling outputs."],
    pipeline,
    screenshot,
    screenshots: enhancedScreenshots,
    seoDetails: {
      titleLength: titleText.length,
      metaLength: metaText.length,
      h1Count,
      wordCount,
      altMissing: Math.max(0, imgCount - altCount),
    },
    serpPreview: {
      title: titleText || "Homepage",
      description: metaText || "",
      url,
    },
    uxScore,
    uxIssuesCount,
    leadGenAnalysis: leadGenResult ? {
      score: leadGenResult.score,
      issues: leadGenResult.issues,
      roiImpact: leadGenResult.roiImpact,
      aboveFoldCta: leadGenResult.aboveFoldCta,
      hasContactForm: leadGenResult.hasContactForm,
      contactFormConfidence: leadGenResult.contactFormConfidence,
      contactFormEvidence: leadGenResult.contactFormEvidence,
    } : undefined,
    deviceResults: deviceResults.length ? deviceResults : undefined,
    manualRulesIssues: [
      ...(uxIssuesCount > 0 ? issues.filter(i => i.title === "Manual UX Heuristic").map(i => i.detail) : []),
      ...(leadGenResult?.issues ?? []),
    ],
    rawHtml: desktopHtml || mobileHtml,
    stageTrace,
  };
}

function withTrace(error: unknown, stageTrace: StageTraceEntry[]) {
  const wrapped = error instanceof Error ? error : new Error(String(error));
  (wrapped as Error & { stageTrace?: StageTraceEntry[] }).stageTrace = [...stageTrace];
  return wrapped;
}

async function withTimeout<T>(fn: () => Promise<T>, timeoutMs: number, stage: string): Promise<T> {
  return await Promise.race([
    fn(),
    new Promise<T>((_, reject) => setTimeout(() => reject(new Error(`${stage} timed out after ${timeoutMs}ms`)), timeoutMs)),
  ]);
}

async function runStageTrace<T>(trace: StageTraceEntry[], stage: string, fn: () => Promise<T>): Promise<T> {
  const started = Date.now();
  const startedAt = new Date(started).toISOString();
  console.log("[pipeline:stage:start]", JSON.stringify({ stage, startedAt }));
  try {
    const result = await fn();
    const ended = Date.now();
    trace.push({
      stage,
      startedAt,
      endedAt: new Date(ended).toISOString(),
      durationMs: ended - started,
      status: "ok",
    });
    console.log("[pipeline:stage:end]", JSON.stringify({ stage, status: "ok", durationMs: ended - started }));
    return result;
  } catch (error) {
    const ended = Date.now();
    trace.push({
      stage,
      startedAt,
      endedAt: new Date(ended).toISOString(),
      durationMs: ended - started,
      status: "failed",
      error: error instanceof Error ? error.message : "unknown",
    });
    console.log("[pipeline:stage:end]", JSON.stringify({ stage, status: "failed", durationMs: ended - started, error: error instanceof Error ? error.message : "unknown" }));
    throw error;
  }
}

async function runLighthouseCli(url: string) {
  const chromePath = chromium.executablePath();
  const args = [
    url,
    "--output=json",
    "--output-path=stdout",
    "--quiet",
    "--only-categories=performance,seo,accessibility,best-practices",
    `--chrome-path=${chromePath}`,
    "--chrome-flags=--headless --no-sandbox --disable-gpu --disable-dev-shm-usage",
  ];

  let stdout = "";
  const lighthouseCliJs = path.join(process.cwd(), "node_modules", "lighthouse", "cli", "index.js");
  try {
    const result = existsSync(lighthouseCliJs)
      ? await execFileAsync(process.execPath, [lighthouseCliJs, ...args], {
          cwd: process.cwd(),
          maxBuffer: 20 * 1024 * 1024,
          timeout: Math.min(21000, LIGHTHOUSE_TIMEOUT_MS + 1000),
          env: process.env,
        })
      : await execFileAsync(
          process.platform === "win32" ? "npx.cmd" : "npx",
          ["lighthouse", ...args],
          {
            cwd: process.cwd(),
            maxBuffer: 20 * 1024 * 1024,
            timeout: Math.min(21000, LIGHTHOUSE_TIMEOUT_MS + 1000),
            env: process.env,
          }
        );
    stdout = result.stdout;
  } catch (primaryError) {
    const primaryStdout = extractExecStdout(primaryError);
    if (primaryStdout && primaryStdout.includes("{")) {
      stdout = primaryStdout;
    } else {
      const fallback = await (process.platform === "win32"
        ? execFileAsync(process.env.ComSpec || "cmd.exe", ["/d", "/s", "/c", `npx lighthouse ${args.map(quoteShellArg).join(" ")}`], {
            cwd: process.cwd(),
            maxBuffer: 20 * 1024 * 1024,
            timeout: Math.min(21000, LIGHTHOUSE_TIMEOUT_MS + 1000),
            env: process.env,
          })
        : execFileAsync("npx", ["lighthouse", ...args], {
            cwd: process.cwd(),
            maxBuffer: 20 * 1024 * 1024,
            timeout: Math.min(21000, LIGHTHOUSE_TIMEOUT_MS + 1000),
            env: process.env,
          })
      ).catch((fallbackError) => {
        const fallbackStdout = extractExecStdout(fallbackError);
        if (fallbackStdout && fallbackStdout.includes("{")) {
          return { stdout: fallbackStdout } as { stdout: string };
        }
        const p = primaryError instanceof Error ? primaryError.message : String(primaryError);
        const f = fallbackError instanceof Error ? fallbackError.message : String(fallbackError);
        throw new Error(`lighthouse launch failed: primary=${p}; fallback=${f}`);
      });
      stdout = fallback.stdout;
    }
  }

  const trimmed = stdout.trim();
  const start = trimmed.indexOf("{");
  if (start < 0) throw new Error("lighthouse stage failed: output missing JSON payload");
  const parsed = JSON.parse(trimmed.slice(start)) as {
    categories?: Record<string, { score: number }>;
    audits?: Record<string, { details?: { screenshot?: { data?: string } } }>;
  };
  return parsed;
}

async function fetchHtmlFallback(url: string): Promise<string> {
  const attempts: Array<HeadersInit | undefined> = [
    {
      "User-Agent": "Mozilla/5.0 (compatible; SiteBlitzLiveAudit/1.0)",
      Accept: "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
      "Accept-Language": "en-US,en;q=0.9",
    },
    undefined,
  ];

  let lastError: unknown;
  for (const headers of attempts) {
    try {
      const res = await fetch(url, {
        method: "GET",
        redirect: "follow",
        headers,
        cache: "no-store",
      });
      if (!res.ok) throw new Error(`http-html returned ${res.status}`);
      const html = await res.text();
      if (!html || html.length < 100) throw new Error("http-html returned insufficient content");
      return html;
    } catch (error) {
      lastError = error;
    }
  }

  throw lastError instanceof Error ? lastError : new Error("http-html fallback failed");
}

function escapeHtml(value: string): string {
  return value
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;")
    .replaceAll("'", "&#39;");
}

function quoteShellArg(arg: string): string {
  const v = String(arg ?? "");
  if (v.length === 0) return '""';
  if (!/[\s"^&|<>]/.test(v)) return v;
  return `"${v.replace(/"/g, '\\"')}"`;
}

function extractExecStdout(error: unknown): string {
  const e = error as { stdout?: unknown };
  const s = typeof e?.stdout === "string" ? e.stdout : "";
  return s;
}

function clampScore(v: number): number {
  return Math.max(0, Math.min(100, Math.round(v)));
}

function estimatePerformanceFallback(input: {
  blockedResponseDetected: boolean;
  hasViewport: boolean;
  scriptCount: number;
  domNodeCount: number;
  customPerformanceSignal: number;
}): number {
  if (input.blockedResponseDetected) return 15;
  const scriptPenalty = Math.min(22, input.scriptCount * 0.35);
  const domPenalty = Math.min(18, Math.max(0, (input.domNodeCount - 900) * 0.008));
  const viewportBoost = input.hasViewport ? 6 : -8;
  return clampScore(input.customPerformanceSignal + viewportBoost - scriptPenalty - domPenalty);
}

function estimateSeoFallback(input: {
  blockedResponseDetected: boolean;
  titlePresent: boolean;
  metaDescriptionPresent: boolean;
  h1Count: number;
  wordCount: number;
}): number {
  if (input.blockedResponseDetected) return 10;
  let score = 38;
  if (input.titlePresent) score += 22;
  if (input.metaDescriptionPresent) score += 20;
  if (input.h1Count === 1) score += 12;
  else if (input.h1Count > 1) score += 6;
  if (input.wordCount >= 250) score += 8;
  return clampScore(score);
}

function estimateAccessibilityFallback(input: {
  blockedResponseDetected: boolean;
  imgCount: number;
  altCount: number;
  axeIssueCount: number;
}): number {
  if (input.blockedResponseDetected) return 12;
  const altRatio = input.imgCount > 0 ? input.altCount / input.imgCount : 1;
  const base = 52 + altRatio * 32;
  const issuePenalty = Math.min(25, input.axeIssueCount * 4);
  return clampScore(base - issuePenalty);
}

